/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.frames;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.AnnotationConfiguration;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;

import java.awt.Color;

import javax.swing.JCheckBox;

/**
 *
 * @author CaioFábio
 */
@SuppressWarnings({ "serial", "unused" })
public class JFrameExample extends javax.swing.JDialog {

    /**
     * Creates new form GUI_cadastro_exame
     */
    
    float aiu = 0;
    float sz = 0;
    
    /**
     * @wbp.parser.constructor
     */
    public JFrameExample(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    JFrameExample(Object object, boolean b, String funcionario_nome, String funcionario_rg, String funcionario_cracha, String funcionario_sexo) {
        
        initComponents();
        
        this.JTF_busca_nome.setText(funcionario_nome);
        this.JTF_busca_rg.setText(funcionario_rg);
        this.JTF_busca_cracha.setText(funcionario_cracha);
        this.JTF_busca_sexo.setText(funcionario_sexo);
        
            Date d = new Date();
            SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
            String data = formatador.format(d);
            JTF_dataevento.setText(data);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    private void initComponents() {

        jPanel37 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel39 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        apresenta_alteracao = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel136 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        JTF_busca_nome = new javax.swing.JTextField();
        JTF_dataevento = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        JTF_busca_rg = new javax.swing.JTextField();
        JTF_busca_cracha = new javax.swing.JTextField();
        jLabel137 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        JTF_busca_sexo = new javax.swing.JTextField();
        jPanel40 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTF_ex66 = new javax.swing.JTextArea();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTF_ex65 = new javax.swing.JTextArea();
        jLabel138 = new javax.swing.JLabel();
        JTF_ex67 = new javax.swing.JTextField();
        JCB_ex67_01 = new javax.swing.JCheckBox();
        JCB_ex67_02 = new javax.swing.JCheckBox();
        JCB_ex67_03 = new javax.swing.JCheckBox();
        jPanel38 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            //    jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               // jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Limpar");

        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               // jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Salvar e Imprimir");

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jButton7.setText("Sair");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              //  jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Salvar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              //  jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Limpar");

        jButton10.setText("Imprimir");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               // jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Salvar e Imprimir");

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap())
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton10)
                    .addComponent(jButton8)
                    .addComponent(jButton11)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vocalexa - Exame Fonoaudiológico");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel136.setText("Nome:");

        jLabel135.setText("RG:");

        JTF_busca_nome.setEditable(false);
        JTF_busca_nome.setBackground(new java.awt.Color(255, 255, 255));
        JTF_busca_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              //  JTF_busca_nomeActionPerformed(evt);
            }
        });

        JTF_dataevento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               // JTF_dataeventoActionPerformed(evt);
            }
        });

        jLabel61.setText("Data:");

        JTF_busca_rg.setEditable(false);
        JTF_busca_rg.setBackground(new java.awt.Color(255, 255, 255));

        JTF_busca_cracha.setEditable(false);
        JTF_busca_cracha.setBackground(new java.awt.Color(255, 255, 255));

        jLabel137.setText("Cracha:");

        jLabel140.setText("Sexo:");

        JTF_busca_sexo.setEditable(false);
        JTF_busca_sexo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel136)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTF_busca_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel135)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTF_busca_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel137)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTF_busca_cracha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel140)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTF_busca_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel61)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTF_dataevento, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(JTF_dataevento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel135)
                    .addComponent(JTF_busca_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel136)
                    .addComponent(JTF_busca_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel137)
                    .addComponent(JTF_busca_cracha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel140)
                    .addComponent(JTF_busca_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel40.setBackground(new java.awt.Color(255, 255, 255));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-session-exit-icon.png"))); // NOI18N
        jButton16.setMnemonic(KeyEvent.VK_3);
        jButton16.setText("Sair (3)");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               // jButton16ActionPerformed(evt);
            }
        });

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save-as-icon.png"))); // NOI18N
        jButton14.setMnemonic(KeyEvent.VK_2);
        jButton14.setText("Salvar (2)");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               // jButton14ActionPerformed(evt);
            }
        });

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder-printer-icon.png"))); // NOI18N
        jButton13.setMnemonic(KeyEvent.VK_1);
        jButton13.setText("Salvar e Imprimir (1)");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               // jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel40Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addGap(19, 19, 19))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel40Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton16)
                    .addComponent(jButton14)
                    .addComponent(jButton13))
                .addContainerGap())
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25Layout.setHorizontalGroup(
        	jPanel25Layout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 315, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
        	jPanel25Layout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 357, Short.MAX_VALUE)
        );
        jPanel25.setLayout(jPanel25Layout);

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));

        JTF_ex66.setColumns(20);
        JTF_ex66.setRows(5);
        jScrollPane2.setViewportView(JTF_ex66);

        jLabel133.setText("Parecer Fonoaudiológico - Eficiência Vocal");

        jLabel134.setText("Conduta");

        JTF_ex65.setColumns(20);
        JTF_ex65.setRows(5);
        jScrollPane1.setViewportView(JTF_ex65);

        jLabel138.setText("Resultado:");

        JCB_ex67_01.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(JCB_ex67_01);
        JCB_ex67_01.setText("Apto");

        JCB_ex67_02.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(JCB_ex67_02);
        JCB_ex67_02.setText("Inapto");

        JCB_ex67_03.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(JCB_ex67_03);
        JCB_ex67_03.setText("Apto com restrições");

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(JCB_ex67_01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCB_ex67_02)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCB_ex67_03))
                    .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel134)
                        .addComponent(jLabel133)
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                        .addComponent(jLabel138)
                        .addComponent(JTF_ex67)))
                .addContainerGap())
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel133)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel134)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel138)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTF_ex67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCB_ex67_01)
                    .addComponent(JCB_ex67_02)
                    .addComponent(JCB_ex67_03))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(186, 186, 186)
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(98, 98, 98))
        );

        jTabbedPane1.addTab("Psicodinâmica III", jPanel24);

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));

        titulo.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LOGO_pequeno.fw.png"))); // NOI18N
        titulo.setText("VOCALEXA - Cadastro de Exames");

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel40, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

//    private void JTF_busca_nomeActionPerformed(java.awt.event.ActionEvent evt) {                                               
//        // TODO add your handling code here:
//    }                                              
//
//    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // TODO add your handling code here:
//        dispose();
//    }                                        
//
//    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        salvar();
//    }                                        
//
//    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // TODO add your handling code here:
//    }                                        
//
//    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // TODO add your handling code here:
//        dispose();
//    }                                        
//
//    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        salvar();
//    }                                        
//
//    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        // TODO add your handling code here:
//    }                                         
//
//    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        salvar();
//    }                                         
//
//    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        // TODO add your handling code here:
//        dispose();
//    }                                         
//
//    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        // TODO add your handling code here:
//        salvar();
//        try {
//            imprimiCadastro();
//        } catch (JRException ex) {
//            Logger.getLogger(GUI_cadastro_exame.class.getName()).log(Level.SEVERE, null, ex);
//        }
 //   }                                         

//    private void JTF_dataeventoActionPerformed(java.awt.event.ActionEvent evt) {                                               
 //       // TODO add your handling code here:
 //           
 //   }                                              

//    private void JTF_ex63_u4FocusGained(java.awt.event.FocusEvent evt) {                                        
//        recebe_valor_u();
//        metodo_valor_aiu();
//        JTF_ex63_s1.requestFocus();
//    }                                       
//
//    private void JTF_ex63_a4FocusGained(java.awt.event.FocusEvent evt) {                                        
//        recebe_valor_a();
//        JTF_ex63_i1.requestFocus();
//    }                                       
//
//    private void JTF_ex63_a4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
//        // TODO add your handling code here:
//    }                                           
//
//    private void JTF_ex63_z4FocusGained(java.awt.event.FocusEvent evt) {                                        
//        recebe_valor_z();
//        metodo_valor_sz();
//    }                                       
//
//    private void JTF_ex63_i4FocusGained(java.awt.event.FocusEvent evt) {                                        
//        recebe_valor_i();
//        JTF_ex63_u1.requestFocus();
//    }                                       
//
//    private void JTF_ex63_s4FocusGained(java.awt.event.FocusEvent evt) {                                        
//        recebe_valor_s();
//        JTF_ex63_z1.requestFocus();
//    }                                       
//
//    private void JTF_ex63_u3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
//        // TODO add your handling code here:
//    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
              /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI_cadastro_exame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI_cadastro_exame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI_cadastro_exame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI_cadastro_exame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /*
         * Create and display the form
         */
   //     java.awt.EventQueue.invokeLater(new Runnable() {
 //           public void run() {
 //               GUI_cadastro_exame dialog = new GUI_cadastro_exame(new javax.swing.JFrame(), true);
   //             dialog.addWindowListener(new java.awt.event.WindowAdapter() {
   //                 @Override
     //               public void windowClosing(java.awt.event.WindowEvent e) {
       //                 System.exit(0);
         //           }
           //     });
             //   dialog.setVisible(true);
            //}
     //   });
    }
    private javax.swing.JCheckBox JCB_ex67_01;
    private javax.swing.JCheckBox JCB_ex67_02;
    private javax.swing.JCheckBox JCB_ex67_03;
    private javax.swing.JTextField JTF_busca_cracha;
    private javax.swing.JTextField JTF_busca_nome;
    private javax.swing.JTextField JTF_busca_rg;
    private javax.swing.JTextField JTF_busca_sexo;
    private javax.swing.JTextField JTF_dataevento;
    private javax.swing.JTextArea JTF_ex65;
    private javax.swing.JTextArea JTF_ex66;
    private javax.swing.JTextField JTF_ex67;
    private javax.swing.ButtonGroup apresenta_alteracao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel titulo;
    // End of variables declaration

//        private void caixa_laringite() {
//        if(JCB_ex11_01_01.isSelected()){
//            JTF_ex11_01_02.setEditable(true);
//            JTF_ex11_01_02.setText("");           
//            JTF_ex11_01_03.setEditable(true);
//            JTF_ex11_01_03.setText("");
//            JTF_ex11_01_04.setEditable(true);
//            JTF_ex11_01_04.setText("");
//        }else{
//            JTF_ex11_01_02.setEditable(false);
//            JTF_ex11_01_02.setText("N/A");
//            JTF_ex11_01_03.setEditable(false);
//            JTF_ex11_01_03.setText("N/A");
//            JTF_ex11_01_04.setEditable(false);
//            JTF_ex11_01_04.setText("N/A");
//        }
//    }
//
//    private void caixa_amigdalite() {
//        if(JCB_ex11_02_01.isSelected()){
//            JTF_ex11_02_02.setEditable(true);
//            JTF_ex11_02_03.setEditable(true);
//            JTF_ex11_02_04.setEditable(true);
//            JTF_ex11_02_02.setText("");
//            JTF_ex11_02_03.setText("");
//            JTF_ex11_02_04.setText("");
//        }else{
//            JTF_ex11_02_02.setEditable(false);
//            JTF_ex11_02_02.setText("N/A");
//            JTF_ex11_02_03.setEditable(false);
//            JTF_ex11_02_03.setText("N/A");
//            JTF_ex11_02_04.setEditable(false);
//            JTF_ex11_02_04.setText("N/A");
//        }
//    }
//
//    private void caixa_faringite() {
//        if(JCB_ex11_03_01.isSelected()){
//            JTF_ex11_03_02.setEditable(true);
//            JTF_ex11_03_02.setText("");
//            JTF_ex11_03_03.setEditable(true);
//            JTF_ex11_03_03.setText("");
//            JTF_ex11_03_04.setEditable(true);
//            JTF_ex11_03_04.setText("");
//        }else{
//            JTF_ex11_03_02.setEditable(false);
//            JTF_ex11_03_02.setText("N/A");
//            JTF_ex11_03_03.setEditable(false);
//            JTF_ex11_03_03.setText("N/A");
//            JTF_ex11_03_04.setEditable(false);
//            JTF_ex11_03_04.setText("N/A");
//        }
//    }
//
//    private void caixa_alergia() {
//        if(JCB_ex11_04_01.isSelected()){
//            JTF_ex11_04_02.setEditable(true);
//            JTF_ex11_04_02.setText("");
//            JTF_ex11_04_03.setEditable(true);
//            JTF_ex11_04_03.setText("");
//            JTF_ex11_04_04.setEditable(true);
//            JTF_ex11_04_04.setText("");
//        }else{
//            JTF_ex11_04_02.setEditable(false);
//            JTF_ex11_04_02.setText("N/A");
//            JTF_ex11_04_03.setEditable(false);
//            JTF_ex11_04_03.setText("N/A");
//            JTF_ex11_04_04.setEditable(false);
//            JTF_ex11_04_04.setText("N/A");
//        }
//    }
//
//    private void caixa_dgh() {
//        if(JCB_ex11_05_01.isSelected()){
//            JTF_ex11_05_02.setEditable(true);
//            JTF_ex11_05_02.setText("");
//            JTF_ex11_05_03.setEditable(true);
//            JTF_ex11_05_03.setText("");
//            JTF_ex11_05_04.setEditable(true);
//            JTF_ex11_05_04.setText("");
//        }else{
//            JTF_ex11_05_02.setEditable(false);
//            JTF_ex11_05_02.setText("N/A");
//            JTF_ex11_05_03.setEditable(false);
//            JTF_ex11_05_03.setText("N/A");
//            JTF_ex11_05_04.setEditable(false);
//            JTF_ex11_05_04.setText("N/A");
//        }
//    }
//
//    private void caixa_ptm() {
//        if(JCB_ex11_06_01.isSelected()){
//            JTF_ex11_06_02.setEditable(true);
//            JTF_ex11_06_03.setEditable(true);
//            JTF_ex11_06_04.setEditable(true);
//            JTF_ex11_06_02.setText("");
//            JTF_ex11_06_03.setText("");
//            JTF_ex11_06_04.setText("");
//        }else{
//            JTF_ex11_06_02.setEditable(false);
//            JTF_ex11_06_02.setText("N/A");
//            JTF_ex11_06_03.setEditable(false);
//            JTF_ex11_06_03.setText("N/A");
//            JTF_ex11_06_04.setEditable(false);
//            JTF_ex11_06_04.setText("N/A");
//        }
//    }
//
//    private void caixa_afoniatotal() {
//        if(JCB_ex11_07_01.isSelected()){
//            JTF_ex11_07_02.setEditable(true);
//            JTF_ex11_07_03.setEditable(true);
//            JTF_ex11_07_04.setEditable(true);
//            JTF_ex11_07_02.setText("");
//            JTF_ex11_07_03.setText("");
//            JTF_ex11_07_04.setText("");
//        }else{
//            JTF_ex11_07_02.setEditable(false);
//            JTF_ex11_07_02.setText("N/A");
//            JTF_ex11_07_03.setEditable(false);
//            JTF_ex11_07_03.setText("N/A");
//            JTF_ex11_07_04.setEditable(false);
//            JTF_ex11_07_04.setText("N/A");
//        }
//    }
//
//    private void caixa_disfonia() {
//        if(JCB_ex11_08_01.isSelected()){
//            JTF_ex11_08_02.setEditable(true);
//            JTF_ex11_08_03.setEditable(true);
//            JTF_ex11_08_04.setEditable(true);
//            JTF_ex11_08_02.setText("");
//            JTF_ex11_08_03.setText("");
//            JTF_ex11_08_04.setText("");
//        }else{
//            JTF_ex11_08_02.setEditable(false);
//            JTF_ex11_08_02.setText("N/A");
//            JTF_ex11_08_03.setEditable(false);
//            JTF_ex11_08_03.setText("N/A");
//            JTF_ex11_08_04.setEditable(false);
//            JTF_ex11_08_04.setText("N/A");
//        }
//    }
//
//    private void caixa_rouquidao() {
//        if(JCB_ex11_09_01.isSelected()){
//            JTF_ex11_09_02.setEditable(true);
//            JTF_ex11_09_03.setEditable(true);
//            JTF_ex11_09_04.setEditable(true);
//            JTF_ex11_09_02.setText("");
//            JTF_ex11_09_03.setText("");
//            JTF_ex11_09_04.setText("");
//        }else{
//            JTF_ex11_09_02.setEditable(false);
//            JTF_ex11_09_02.setText("N/A");
//            JTF_ex11_09_03.setEditable(false);
//            JTF_ex11_09_03.setText("N/A");
//            JTF_ex11_09_04.setEditable(false);
//            JTF_ex11_09_04.setText("N/A");
//        }
//    }
//
//    private void caixa_resfriados() {
//        if(JCB_ex11_10_01.isSelected()){
//            JTF_ex11_10_02.setEditable(true);
//            JTF_ex11_10_03.setEditable(true);
//            JTF_ex11_10_04.setEditable(true);
//            JTF_ex11_10_02.setText("");
//            JTF_ex11_10_03.setText("");
//            JTF_ex11_10_04.setText("");
//        }else{
//            JTF_ex11_10_02.setEditable(false);
//            JTF_ex11_10_02.setText("N/A");
//            JTF_ex11_10_03.setEditable(false);
//            JTF_ex11_10_03.setText("N/A");
//            JTF_ex11_10_04.setEditable(false);
//            JTF_ex11_10_04.setText("N/A");
//        }
//    }
//
//    private void recebe_valor_a() {
//        float a1 = Float.parseFloat(JTF_ex63_a1.getText());
//        float a2 = Float.parseFloat(JTF_ex63_a2.getText());
//        float a3 = Float.parseFloat(JTF_ex63_a3.getText());
//        float a4 = (a1+a2+a3)/3;
//        DecimalFormat df = new DecimalFormat("00.00");
//        String a5 = df.format(a4);
//        this.JTF_ex63_a4.setText(String.valueOf(a5).replaceAll(",", "."));
//    }
//
//    private void recebe_valor_i() {
//        float i1 = Float.parseFloat(JTF_ex63_i1.getText());
//        float i2 = Float.parseFloat(JTF_ex63_i2.getText());
//        float i3 = Float.parseFloat(JTF_ex63_i3.getText());
//        float i4 = (i1+i2+i3)/3;
//        DecimalFormat df = new DecimalFormat("00.00");
//        String i5 = df.format(i4);
//        this.JTF_ex63_i4.setText(String.valueOf(i5).replaceAll(",", "."));
//    }
//
//    private void recebe_valor_u() {
//        float u1 = Float.parseFloat(JTF_ex63_u1.getText());
//        float u2 = Float.parseFloat(JTF_ex63_u2.getText());
//        float u3 = Float.parseFloat(JTF_ex63_u3.getText());
//        float u4 = (u1+u2+u3)/3;
//        DecimalFormat df = new DecimalFormat("00.00");
//        String u5 = df.format(u4);
//        this.JTF_ex63_u4.setText(String.valueOf(u5).replaceAll(",", "."));
//    }
//
//    private void recebe_valor_s() {
//        float s1 = Float.parseFloat(JTF_ex63_s1.getText());
//        float s2 = Float.parseFloat(JTF_ex63_s2.getText());
//        float s3 = Float.parseFloat(JTF_ex63_s3.getText());
//        float s4 = (s1+s2+s3)/3;
//        DecimalFormat df = new DecimalFormat("00.00");
//        String s5 = df.format(s4);
//        this.JTF_ex63_s4.setText(String.valueOf(s5).replaceAll(",", "."));
//    }
//
//    private void recebe_valor_z() {
//        float z1 = Float.parseFloat(JTF_ex63_z1.getText());
//        float z2 = Float.parseFloat(JTF_ex63_z2.getText());
//        float z3 = Float.parseFloat(JTF_ex63_z3.getText());
//        float z4 = (z1+z2+z3)/3;
//        DecimalFormat df = new DecimalFormat("00.00");
//        String z5 = df.format(z4);
//        this.JTF_ex63_z4.setText(String.valueOf(z5).replaceAll(",", "."));
//    }
//
//    private void salvar() {
//            SessionFactory sf = new AnnotationConfiguration().configure().buildSessionFactory();
//	
//        Session s = sf.openSession();
//		
//		s.beginTransaction();
//		
//		Exames c = new Exames();
//                
//                c.setEx_rg(JTF_busca_rg.getText());
//                c.setEx_data(JTF_dataevento.getText());
//            // Histórico Pessoal
//                c.setEx01(JTF_ex01.getText());
//            // As variações de humor alteram a voz
//                c.setEx02(JTF_ex02.getText());
//            // Ao fim do dia sua voz esta
//                    String ex_03 = "";
//                if(JCB_ex03_1.isSelected()){
//                    ex_03 += "Igual ao início do dia. ";
//                }
//                if(JCB_ex03_2.isSelected()){
//                    ex_03 += "Mais rouca que no início do dia. ";
//                }
//                if(JCB_ex03_3.isSelected()){
//                    ex_03 += "Mais cansada que no início do dia. ";
//                }
//                if(JCB_ex03_4.isSelected()){
//                    ex_03 += "Mais fraca que ao início do dia. ";
//                }
//                if(JCB_ex03_5.isSelected()){
//                    ex_03 += "Mais agradável que no início do dia. ";
//                }
//                    c.setEx03(ex_03);
//            //Os gargarejos melhoram a voz
//                c.setEx04(JTF_ex04.getText());
//            //As pessoas costumam dizer que
//                String ex_05 = "";
//                if(JCB_ex05_01.isSelected()){
//                    ex_05 += "Você fala alto. ";
//                }
//                if(JCB_ex05_02.isSelected()){
//                    ex_05 += "Você tem voz estridente. ";
//                }
//                if(JCB_ex05_03.isSelected()){
//                    ex_05 += "Quase não se ouve o que você diz. ";
//                }
//                if(JCB_ex05_04.isSelected()){
//                    ex_05 += "Você fala baixo. ";
//                }
//                if(JCB_ex05_05.isSelected()){
//                    ex_05 += "Quase não se entende o que você diz. ";
//                }
//                if(JCB_ex05_06.isSelected()){
//                    ex_05 += "Não há comentários. ";
//                }
//                    c.setEx05(ex_05);
//            //Como você ouve sua voz
//                c.setEx06(JTF_ex06.getText());
//            //Gosta dela? Porque?
//                c.setEx07(JTF_ex07.getText());
//            //Alguem em sua familia apresenta algum problema vocal? Qual?
//                c.setEx08(JTF_ex08.getText());
//            //A sua voz parece mais com
//                c.setEx09(JTF_ex09.getText());
//            //Observacao
//                c.setEx10(JTF_ex10.getText());
//            //Quadros
//                
//                //Laringite - 01
//                    if(JCB_ex11_01_01.isSelected()){
//                        c.setEx11_01_01("Sim");
//                        c.setEx11_01_02(JTF_ex11_01_02.getText());
//                        c.setEx11_01_03(JTF_ex11_01_03.getText());
//                        c.setEx11_01_04(JTF_ex11_01_03.getText());
//                    }else{
//                        c.setEx11_01_01("Não");
//                        c.setEx11_01_02(JTF_ex11_01_02.getText());
//                        c.setEx11_01_03(JTF_ex11_01_03.getText());
//                        c.setEx11_01_04(JTF_ex11_01_03.getText());
//                    }
//                //Amigdalite - 02
//                    if(JCB_ex11_02_01.isSelected()){
//                        c.setEx11_02_01("Sim");
//                        c.setEx11_02_02(JTF_ex11_02_02.getText());
//                        c.setEx11_02_03(JTF_ex11_02_03.getText());
//                        c.setEx11_02_04(JTF_ex11_02_03.getText());
//                    }else{
//                        c.setEx11_02_01("Não");
//                        c.setEx11_02_02(JTF_ex11_02_02.getText());
//                        c.setEx11_02_03(JTF_ex11_02_03.getText());
//                        c.setEx11_02_04(JTF_ex11_02_03.getText());
//                    }
//                //Faringite - 03
//                    if(JCB_ex11_03_01.isSelected()){
//                        c.setEx11_03_01("Sim");
//                        c.setEx11_03_02(JTF_ex11_03_02.getText());
//                        c.setEx11_03_03(JTF_ex11_03_03.getText());
//                        c.setEx11_03_04(JTF_ex11_03_03.getText());
//                    }else{
//                        c.setEx11_03_01("Não");
//                        c.setEx11_03_02(JTF_ex11_03_02.getText());
//                        c.setEx11_03_03(JTF_ex11_03_03.getText());
//                        c.setEx11_03_04(JTF_ex11_03_03.getText());
//                    }
//                //Alergia - 04
//                    if(JCB_ex11_04_01.isSelected()){
//                        c.setEx11_04_01("Sim");
//                        c.setEx11_04_02(JTF_ex11_04_02.getText());
//                        c.setEx11_04_03(JTF_ex11_04_03.getText());
//                        c.setEx11_04_04(JTF_ex11_04_03.getText());
//                    }else{
//                        c.setEx11_04_01("Não");
//                        c.setEx11_04_02(JTF_ex11_04_02.getText());
//                        c.setEx11_04_03(JTF_ex11_04_03.getText());
//                        c.setEx11_04_04(JTF_ex11_04_03.getText());
//                    }
//                //Dist Gland horm - 05             
//                    if(JCB_ex11_05_01.isSelected()){
//                        c.setEx11_05_01("Sim");
//                        c.setEx11_05_02(JTF_ex11_05_02.getText());
//                        c.setEx11_05_03(JTF_ex11_05_03.getText());
//                        c.setEx11_05_04(JTF_ex11_05_03.getText());
//                    }else{
//                        c.setEx11_05_01("Não");
//                        c.setEx11_05_02(JTF_ex11_05_02.getText());
//                        c.setEx11_05_03(JTF_ex11_05_03.getText());
//                        c.setEx11_05_04(JTF_ex11_05_03.getText());
//                    }
//                //Prob Tem Mand - 06
//                    if(JCB_ex11_06_01.isSelected()){
//                        c.setEx11_06_01("Sim");
//                        c.setEx11_06_02(JTF_ex11_06_02.getText());
//                        c.setEx11_06_03(JTF_ex11_06_03.getText());
//                        c.setEx11_06_04(JTF_ex11_06_03.getText());
//                    }else{
//                        c.setEx11_06_01("Não");
//                        c.setEx11_06_02(JTF_ex11_06_02.getText());
//                        c.setEx11_06_03(JTF_ex11_06_03.getText());
//                        c.setEx11_06_04(JTF_ex11_06_03.getText());
//                    }
//                //Afonia Total - 07
//                    if(JCB_ex11_07_01.isSelected()){
//                        c.setEx11_07_01("Sim");
//                        c.setEx11_07_02(JTF_ex11_07_02.getText());
//                        c.setEx11_07_03(JTF_ex11_07_03.getText());
//                        c.setEx11_07_04(JTF_ex11_07_03.getText());
//                    }else{
//                        c.setEx11_07_01("Não");
//                        c.setEx11_07_02(JTF_ex11_07_02.getText());
//                        c.setEx11_07_03(JTF_ex11_07_03.getText());
//                        c.setEx11_07_04(JTF_ex11_07_03.getText());
//                    }
//                //Disfonia >3 dias = 08
//                    if(JCB_ex11_08_01.isSelected()){
//                        c.setEx11_08_01("Sim");
//                        c.setEx11_08_02(JTF_ex11_08_02.getText());
//                        c.setEx11_08_03(JTF_ex11_08_03.getText());
//                        c.setEx11_08_04(JTF_ex11_08_03.getText());
//                    }else{
//                        c.setEx11_08_01("Não");
//                        c.setEx11_08_02(JTF_ex11_08_02.getText());
//                        c.setEx11_08_03(JTF_ex11_08_03.getText());
//                        c.setEx11_08_04(JTF_ex11_08_03.getText());
//                    }
//                //Rouquidão após um longo período de jogos festas... - 09
//                    if(JCB_ex11_09_01.isSelected()){
//                        c.setEx11_09_01("Sim");
//                        c.setEx11_09_02(JTF_ex11_09_02.getText());
//                        c.setEx11_09_03(JTF_ex11_09_03.getText());
//                        c.setEx11_09_04(JTF_ex11_09_03.getText());
//                    }else{
//                        c.setEx11_09_01("Não");
//                        c.setEx11_09_02(JTF_ex11_09_02.getText());
//                        c.setEx11_09_03(JTF_ex11_09_03.getText());
//                        c.setEx11_09_04(JTF_ex11_09_03.getText());
//                    }
//                //Resfriados frequentes - 10
//                    if(JCB_ex11_10_01.isSelected()){
//                        c.setEx11_10_01("Sim");
//                        c.setEx11_10_02(JTF_ex11_10_02.getText());
//                        c.setEx11_10_03(JTF_ex11_10_03.getText());
//                        c.setEx11_10_04(JTF_ex11_10_03.getText());
//                    }else{
//                        c.setEx11_10_01("Não");
//                        c.setEx11_10_02(JTF_ex11_10_02.getText());
//                        c.setEx11_10_03(JTF_ex11_10_03.getText());
//                        c.setEx11_10_04(JTF_ex11_10_03.getText());
//                    }
//            //Ao falar sente
//                    String ex_12 = "";
//                    if(JCB_ex12_01.isSelected()){
//                        ex_12 += "Fadiga ao falar. ";
//                    }
//                    if(JCB_ex12_02.isSelected()){
//                        ex_12 += "Aperto. ";
//                    }
//                    if(JCB_ex12_03.isSelected()){
//                        ex_12 += "Tensão em região cervical. ";
//                    }
//                    if(JCB_ex12_04.isSelected()){
//                        ex_12 += "Tosse. ";
//                    }
//                    if(JCB_ex12_05.isSelected()){
//                        ex_12 += "Dor na garganta. ";
//                    }
//                    if(JCB_ex12_06.isSelected()){
//                        ex_12 += "Ardência. ";
//                    }
//                    if(JCB_ex12_07.isSelected()){
//                        ex_12 += "Fisgadas. ";
//                    }
//                    if(JCB_ex12_08.isSelected()){
//                        ex_12 += "Pigarro. ";
//                    }
//                    if(JCB_ex12_09.isSelected()){
//                        ex_12 += "Secura. ";
//                    }
//                    if(JCB_ex12_10.isSelected()){
//                        ex_12 += "Sensação de corpo estranho. ";
//                    }
//                    if(JCB_ex12_11.isSelected()){
//                        ex_12 += "Falta de ar. ";
//                    }
//                    if(JCB_ex12_12.isSelected()){
//                        ex_12 += "Coceira. ";
//                    }
//                    if(JCB_ex12_14.isSelected()){
//                        ex_12 += "Aflição. ";
//                    }
//                 c.setEx12(ex_12);
//            //Pratica atividades físicas
//                 c.setEx13(JTF_ex13.getText());
//            //Hábitos de vida diária (alteram a voz)
//                 String ex_14 = "";
//                 if(JCB_ex14_01.isSelected()){
//                     ex_14 += "Alcool. ";
//                 }
//                 if(JCB_ex14_02.isSelected()){
//                     ex_14 += "Fumo. ";
//                 }
//                 if(JCB_ex14_03.isSelected()){
//                     ex_14 += "Bebidas frias. ";
//                 }
//                 if(JCB_ex14_04.isSelected()){
//                     ex_14 += "Bebidas quentes. ";
//                 }
//                 if(JCB_ex14_05.isSelected()){
//                     ex_14 += "Clima frio. ";
//                 }
//                 if(JCB_ex14_06.isSelected()){
//                     ex_14 += "Clima quente. ";
//                 }
//                 if(JCB_ex14_07.isSelected()){
//                     ex_14 += "Toxicos. ";
//                 }
//                 if(JCB_ex14_08.isSelected()){
//                     ex_14 += "Outros";
//                 }
//                    c.setEx14(ex_14);
//            //Observações
//                    c.setEx15(JTF_ex15.getText());
//            //Frequenta festas, bailes, lugares que tocam musicas altas? com que frequencia?
//                    c.setEx16(JTF_ex16.getText());
//            //Gosta de cantar, já participou de atividade que envolvam canto? cite
//                    c.setEx17(JTF_ex17.getText());
//            //Uso de medicamentos continuos
//              if (JCB_ex17_1.isSelected()) {
//            c.setEx17_1(JTF_ex17_1.getText());
//        } else {
//            c.setEx17_1("Não.");
//        }
//            //Em casa
//                    String ex18 = "";
//                    if(JCB_ex18_01.isSelected()){
//                        ex18 += "Fala muito. ";
//                    }
//                    if(JCB_ex18_02.isSelected()){
//                        ex18 += "Grita. ";
//                    }
//                    if(JCB_ex18_03.isSelected()){
//                        ex18 += "Fala pouco. ";
//                    }
//                    if(JCB_ex18_04.isSelected()){
//                        ex18 += "Brinca com a voz. ";
//                    }
//                    if(JCB_ex18_05.isSelected()){
//                        ex18 += "Se exalta com frequência. ";
//                    }
//                    if(JCB_ex18_06.isSelected()){
//                        ex18 += "Fala muito ao telefone. ";
//                    }
//                    if(JCB_ex18_07.isSelected()){
//                        ex18 += "Canta. ";
//                    }
//                    if(JCB_ex18_08.isSelected()){
//                        ex18 += "Faz imitações. ";
//                    }
//                    c.setEx18(ex18);
//            //No Trabalho
//                    String ex19 = "";
//                    if(JCB_ex19_01.isSelected()){
//                        ex19 += "Fala muito. ";
//                    }
//                    if(JCB_ex19_02.isSelected()){
//                        ex19 += "Grita. ";
//                    }
//                    if(JCB_ex19_03.isSelected()){
//                        ex19 += "Fala pouco. ";
//                    }
//                    if(JCB_ex19_04.isSelected()){
//                        ex19 += "Brinca com a voz. ";
//                    }
//                    if(JCB_ex19_05.isSelected()){
//                        ex19 += "Se exalta com frequência. ";
//                    }
//                    if(JCB_ex19_06.isSelected()){
//                        ex19 += "Fala muito ao telefone. ";
//                    }
//                    if(JCB_ex19_07.isSelected()){
//                        ex19 += "Canta. ";
//                    }
//                    if(JCB_ex19_08.isSelected()){
//                        ex19 += "Faz imitações. ";
//                    }
//                    c.setEx19(ex19);
//            //No caso de ser profissional da voz, fala em media quantas horas por dia?
//                    c.setEx20(JTF_ex20.getText());
//            //Características pessoais
//                    String ex21 = "";
//                    if(JCB_ex21_01.isSelected()){
//                        ex21 += "Calma. ";
//                    }
//                    if(JCB_ex21_02.isSelected()){
//                        ex21 += "Ponderada. ";
//                    }
//                    if(JCB_ex21_03.isSelected()){
//                        ex21 += "Irritada. ";
//                    }
//                    if(JCB_ex21_04.isSelected()){
//                        ex21 += "Agitada. ";
//                    }
//                    if(JCB_ex21_05.isSelected()){
//                        ex21 += "Estressada. ";
//                    }
//                    if(JCB_ex21_06.isSelected()){
//                        ex21 += "Timida. ";
//                    }
//                    if(JCB_ex21_07.isSelected()){
//                        ex21 += "Ansiosa. ";
//                    }
//                    if(JCB_ex21_08.isSelected()){
//                        ex21 += "Extrovertida. ";
//                    }
//                    c.setEx21(ex21);
//            //Fica exposto ao ar condicionado fora do ambiente laboral?
//                    c.setEx22(JTF_ex22.getText());
//            //Antecedentes Pessoais
//                    String ex23 = "";
//                    if(JCB_ex23_01.isSelected()){
//                        ex23 += "Retirada de amígdalas. ";
//                    }
//                    if(JCB_ex23_02.isSelected()){
//                        ex23 += JTF_ex23_02.getText()+". ";
//                    }
//                    if(JCB_ex23_03.isSelected()){
//                        ex23 += "Bronquite. ";
//                    }
//                    if(JCB_ex23_04.isSelected()){
//                        ex23 += "Problemas oclusais. ";
//                    }
//                    if(JCB_ex23_05.isSelected()){
//                        ex23 += "Engasgos frequentes. ";
//                    }
//                    if(JCB_ex23_06.isSelected()){
//                        ex23 += "Gastrite. ";
//                    }
//                    if(JCB_ex23_07.isSelected()){
//                        ex23 += "Sudorese intensa. ";
//                    }
//                    if(JCB_ex23_08.isSelected()){
//                        ex23 += "Retirada de adenóides. ";
//                    }
//                    if(JCB_ex23_09.isSelected()){
//                        ex23 += JTF_ex23_09.getText()+". ";
//                    }
//                    if(JCB_ex23_10.isSelected()){
//                        ex23 += "Aftas. ";
//                    }
//                    if(JCB_ex23_11.isSelected()){
//                        ex23 += "Problemas dentários. ";
//                    }
//                    if(JCB_ex23_12.isSelected()){
//                        ex23 += "Disfagia. ";
//                    }
//                    if(JCB_ex23_13.isSelected()){
//                        ex23 += "Constipação intestinal. ";
//                    }
//                    if(JCB_ex23_14.isSelected()){
//                        ex23 += "Mãos frias. ";
//                    }
//                    if(JCB_ex23_15.isSelected()){
//                        ex23 += "Cirurgia em PPVV. ";
//                    }
//                    if(JCB_ex23_16.isSelected()){
//                        ex23 += "Asma. ";
//                    }
//                    if(JCB_ex23_17.isSelected()){
//                        ex23 += "Estomatites. ";
//                    }
//                    if(JCB_ex23_18.isSelected()){
//                        ex23 += "Onicofagia. ";
//                    }
//                    if(JCB_ex23_19.isSelected()){
//                        ex23 += "RGE. ";
//                    }
//                    if(JCB_ex23_20.isSelected()){
//                        ex23 += "Taquicardia. ";
//                    }
//                    c.setEx23(ex23);
//            //Traumas recentes
//                    c.setEx24(JTF_ex24.getText());
//            //Alguma associação do trauma com a voz
//                    c.setEx25(JTF_ex25.getText());
//            //Outras relações do emocional com a voz
//                    c.setEx26(JTF_ex26.getText());
//            //Habitos alimentares
//                    String ex27 = "";
//                    if(JCB_ex27_01.isSelected()){
//                        ex27 += "Água, " + JTF_ex27_01.getText() + ". ";
//                    }
//                    if(JCB_ex27_02.isSelected()){
//                        ex27 += "Doce. ";
//                    }
//                    if(JCB_ex27_03.isSelected()){
//                        ex27 += "Chocolate. ";
//                    }
//                    if(JCB_ex27_04.isSelected()){
//                        ex27 += "Pimenta. ";
//                    }
//                    if(JCB_ex27_05.isSelected()){
//                        ex27 += "Gelada. ";
//                    }
//                    if(JCB_ex27_06.isSelected()){
//                        ex27 += "Própolis. ";
//                    }
//                    if(JCB_ex27_07.isSelected()){
//                        ex27 += "Chimarrão. ";
//                    }
//                    if(JCB_ex27_08.isSelected()){
//                        ex27 += "Gengibre. ";
//                    }
//                    if(JCB_ex27_09.isSelected()){
//                        ex27 += "Café. ";
//                    }
//                    if(JCB_ex27_10.isSelected()){
//                        ex27 += "Chá mate. ";
//                    }
//                    if(JCB_ex27_11.isSelected()){
//                        ex27 += "Leite. ";
//                    }
//                    if(JCB_ex27_12.isSelected()){
//                        ex27 += "Maçã. ";
//                    }
//                    if(JCB_ex27_13.isSelected()){
//                        ex27 += "Tererê. ";
//                    }
//                    if(JCB_ex27_14.isSelected()){
//                        ex27 += "Refrigerante. ";
//                    }
//                    if(JCB_ex27_15.isSelected()){
//                        ex27 += "Derivados de leite. ";
//                    }
//                    if(JCB_ex27_16.isSelected()){
//                        ex27 += "Uso de pastilhas. ";
//                    }
//                    c.setEx27(ex27);
//            //Ao ter que se apresentar/debater um assunto frente a um 
//            //grupo/platéia qual a sua reação
//                    c.setEx28(JTF_ex28.getText());
//            //Convivência social
//                    String ex29 = "";
//                    if(JCB_ex29_01.isSelected()){
//                        ex29 += "Com grupo de amigos. ";
//                    }
//                    if(JCB_ex29_02.isSelected()){
//                        ex29 += "Poucos amigos. ";
//                    }
//                    if(JCB_ex29_03.isSelected()){
//                        ex29 += "Com familiares. ";
//                    }
//                    c.setEx29(ex29);
//            //Relaxa
//                    String ex30 = "";
//                    if(JCB_ex30_01.isSelected()){
//                        ex30 += "Música. ";
//                    }
//                    if(JCB_ex30_02.isSelected()){
//                        ex30 += "Cinema. ";
//                    }
//                    if(JCB_ex30_03.isSelected()){
//                        ex30 += "TV. ";
//                    }
//                    if(JCB_ex30_04.isSelected()){
//                        ex30 += "Leitura. ";
//                    }
//                    if(JCB_ex30_05.isSelected()){
//                        ex30 += "Massagem. ";
//                    }
//                    if(JCB_ex30_06.isSelected()){
//                        ex30 += JTF_ex30_06.getText()+". ";
//                    }
//                    if(JCB_ex30_07.isSelected()){
//                        ex30 += "Não relaxa. ";
//                    }
//                    c.setEx30(ex30);
//            //Sono
//                    String ex31 = "";
//                    if(JCB_ex31_01.isSelected()){
//                        ex31 += "Tranquilo. ";
//                    }
//                    if(JCB_ex31_01.isSelected()){
//                        ex31 += "Agitado. ";
//                    }
//                    if(JCB_ex31_01.isSelected()){
//                        ex31 += "Acorda com frequência. ";
//                    }
//                    if(JCB_ex31_01.isSelected()){
//                        ex31 += "Insônia. ";
//                    }
//                    c.setEx31(ex31);
//            //Vestuário
//                    c.setEx32(JTF_ex32.getText());
//            //Observações
//                    c.setEx33(JTF_ex33.getText());
//            //Contato visual
//                    c.setEx34(JTF_ex34.getText());
//            //Impressões pessoais
//                    c.setEx35(JTF_ex35.getText());
//            //Tipo de voz
//                    String ex36 = "";
//                    if(JCB_ex36_01.isSelected()){
//                        ex36 += "Rouca. ";
//                    }
//                    if(JCB_ex36_02.isSelected()){
//                        ex36 += "Pastosa. ";
//                    }
//                    if(JCB_ex36_03.isSelected()){
//                        ex36 += "Comprimida. ";
//                    }
//                    if(JCB_ex36_04.isSelected()){
//                        ex36 += "Monótona. ";
//                    }
//                    if(JCB_ex36_05.isSelected()){
//                        ex36 += "Crepitante. ";
//                    }
//                    if(JCB_ex36_06.isSelected()){
//                        ex36 += "Hipernasal. ";
//                    }
//                    if(JCB_ex36_07.isSelected()){
//                        ex36 += "Sussurrada. ";
//                    }
//                    if(JCB_ex36_08.isSelected()){
//                        ex36 += "Áspera. ";
//                    }
//                    if(JCB_ex36_09.isSelected()){
//                        ex36 += "Bitonal. ";
//                    }
//                    if(JCB_ex36_10.isSelected()){
//                        ex36 += "Soprosa. ";
//                    }
//                    if(JCB_ex36_11.isSelected()){
//                        ex36 += "Trêmula. ";
//                    }
//                    if(JCB_ex36_12.isSelected()){
//                        ex36 += "Virilizada. ";
//                    }
//                    if(JCB_ex36_13.isSelected()){
//                        ex36 += "Hiponasal. ";
//                    }
//                    if(JCB_ex36_14.isSelected()){
//                        ex36 += "Fluída. ";
//                    }
//                    if(JCB_ex36_15.isSelected()){
//                        ex36 += "Tensa-estrangulada. ";
//                    }
//                    if(JCB_ex36_16.isSelected()){
//                        ex36 += "Infantilizada. ";
//                    }
//                    if(JCB_ex36_17.isSelected()){
//                        ex36 += "Diplofônica. ";
//                    }
//                    if(JCB_ex36_18.isSelected()){
//                        ex36 += "Feminilizada. ";
//                    }
//                    if(JCB_ex36_19.isSelected()){
//                        ex36 += "Nasalidade mista. ";
//                    }
//                    if(JCB_ex36_20.isSelected()){
//                        ex36 += "Glutural. ";
//                    }
//                    if(JCB_ex36_21.isSelected()){
//                        ex36 += "Branca. ";
//                    }
//                    if(JCB_ex36_22.isSelected()){
//                        ex36 += "Polifônica. ";
//                    }
//                    if(JCB_ex36_23.isSelected()){
//                        ex36 += "Presbifônica. ";
//                    }
//                    if(JCB_ex36_24.isSelected()){
//                        ex36 += JTF_ex36_24.getText()+". ";
//                    }
//                    if(JCB_ex36_25.isSelected()){
//                        ex36 += "Normal. ";
//                    }
//                    c.setEx36(ex36);
//            //Alteração da voz com movimento da cabeça
//                    String ex37 = "";
//                    if(JCB_ex37.isSelected()){
//                        ex37 = "Sim";
//                    }else{
//                        ex37 = "Não";
//                    }
//                    c.setEx37(ex37);
//            //Sistema de ressonância
//                    String ex38 = "";
//                    if(JCB_ex38_01.isSelected()){
//                        ex38 += "Uso equilibrado. ";
//                    }
//                    if(JCB_ex38_02.isSelected()){
//                        ex38 += "Uso insuficiente da cavidade nasal. ";
//                    }
//                    if(JCB_ex38_03_1.isSelected()){
//                        ex38 += "Uso excessivo da faringe. ";
//                    }
//                    if(JCB_ex38_03_2.isSelected()){
//                        ex38 += "Uso excessivo da laringe. ";
//                    }
//                    if(JCB_ex38_03_3.isSelected()){
//                        ex38 += "Uso excessivo nasal. ";
//                    }
//                    if(JCB_ex38_04.isSelected()){
//                        ex38 += "Uso equilibrado. ";
//                    }
//                    c.setEx38(ex38);
//            //Ataque vocal
//                    String ex39 = "";
//                    if(JCB_ex39_01.isSelected()){
//                        ex39 += "Isocrônico. ";
//                    }
//                    if(JCB_ex39_02.isSelected()){
//                        ex39 += "Brusco. ";
//                    }
//                    if(JCB_ex39_03.isSelected()){
//                        ex39 += "Aspirado. ";
//                    }
//                    if(JCB_ex39_04.isSelected()){
//                        ex39 += "Uso alternado. ";
//                    }
//                    c.setEx39(ex39);
//            //Qualidade de emissão
//                    String ex40 = "";
//                    if(JCB_ex40_01.isSelected()){
//                        ex40 += "Estabilidade. ";
//                    }
//                    if(JCB_ex40_02.isSelected()){
//                        ex40 += "Decréscimo de altura. ";
//                    }
//                    if(JCB_ex40_03.isSelected()){
//                        ex40 += "Usa a reserva respiratória. ";
//                    }
//                    if(JCB_ex40_04.isSelected()){
//                        ex40 += "Quebras de sonoridade. ";
//                    }
//                    if(JCB_ex40_05.isSelected()){
//                        ex40 += "Decréscimo de intensidade. ";
//                    }
//                    if(JCB_ex40_06.isSelected()){
//                        ex40 += "Bitonalidade. ";
//                    }
//                    if(JCB_ex40_07.isSelected()){
//                        ex40 += "Flutuações. ";
//                    }
//                    c.setEx40(ex40);
//            //Pitch
//                    String ex41 = "";
//                    if(JCB_ex41_01.isSelected()){
//                        ex41 += "Normal. ";
//                    }
//                    if(JCB_ex41_02.isSelected()){
//                        ex41 += "Agudo. ";
//                    }
//                    if(JCB_ex41_03.isSelected()){
//                        ex41 += "Grave. ";
//                    }
//                    c.setEx41(ex41);
//            //Loudness (Sensação psicofísica da intensidade vocal)
//                    String ex42 = "";
//                    if(JCB_ex42_01.isSelected()){
//                        ex42 += "Aumentado. ";
//                    }
//                    if(JCB_ex42_02.isSelected()){
//                        ex42 += "Diminuído. ";
//                    }
//                    if(JCB_ex42_03.isSelected()){
//                        ex42 += "Adequado. ";
//                    }
//                    c.setEx42(ex42);
//            // Modulação da intensidade
//                    String ex43 = "";
//                    if(JCB_ex43_01.isSelected()){
//                        ex43 += "Adequada. ";
//                    }
//                    if(JCB_ex43_02.isSelected()){
//                        ex43 += "Restrita com condição de modular. ";
//                    }
//                    if(JCB_ex43_03.isSelected()){
//                        ex43 += "Repetitiva. ";
//                    }
//                    if(JCB_ex43_04.isSelected()){
//                        ex43 += "Restrita sem condição de modular. ";
//                    }
//                    if(JCB_ex43_05.isSelected()){
//                        ex43 += "Excessiva. ";
//                    }
//                    c.setEx43(ex43);
//            //Articulação
//                    String ex44 = "";
//                    if(JCB_ex44_01.isSelected()){
//                        ex44 += "Precisa. ";                        
//                    }
//                    if(JCB_ex44_02.isSelected()){
//                        ex44 += "Hipertensa. ";                        
//                    }
//                    if(JCB_ex44_03.isSelected()){
//                        ex44 += "Indiferenciada. ";                        
//                    }
//                    if(JCB_ex44_04.isSelected()){
//                        ex44 += "Hipotensa. ";                        
//                    }
//                    if(JCB_ex44_05.isSelected()){
//                        ex44 += "Exagerada. ";                        
//                    }
//                    if(JCB_ex44_06.isSelected()){
//                        ex44 += "Marcante. ";                        
//                    }
//                    if(JCB_ex44_07.isSelected()){
//                        ex44 += "Reduzida. ";                        
//                    }
//                    if(JCB_ex44_08.isSelected()){
//                        ex44 += "Prejudicada. ";                        
//                    }
//                    c.setEx44(ex44);
//            //Distúrbios Articulatórios
//                    String ex45 = "";
//                    if(JCB_ex45_02.isSelected()){
//                        ex45 += "Sigmatismo anterior. ";
//                    }
//                    if(JCB_ex45_03.isSelected()){
//                        ex45 += "Sigmatismo lateral. ";
//                    }
//                    if(JCB_ex45_04.isSelected()){
//                        ex45 += "Línguo-dentais. ";
//                    }
//                    if(JCB_ex45_01.isSelected()){
//                        ex45 += "Normal. ";
//                    }
//                    if(JCB_ex45_05.isSelected()){
//                        ex45 += JTF_ex45_05.getText()+". ";
//                    }
//                    c.setEx45(ex45);
//            //CPFA
//                    String ex46 = "";
//                    if(JCB_ex46_01.isSelected()){
//                        ex46 += "Adequado. ";
//                    }
//                    if(JCB_ex46_02.isSelected()){
//                        ex46 += "Hipertonia-Laríngea. ";
//                    }
//                    if(JCB_ex46_03.isSelected()){
//                        ex46 += "Insuficiência. ";
//                    }
//                    if(JCB_ex46_04.isSelected()){
//                        ex46 += JTF_ex46_04.getText()+". ";
//                    }
//                    c.setEx46(ex46);
//            //Pronuncia
//                    String ex47 = "";
//                    if(JCB_ex47_01.isSelected()){
//                        ex47 += "Normal. ";
//                    }
//                    if(JCB_ex47_02.isSelected()){
//                        ex47 += "Regionalismos. ";
//                    }
//                    if(JCB_ex47_03.isSelected()){
//                        ex47 += "Sotaques. ";
//                    }
//                    c.setEx47(ex47);
//            //Velocidade da fala
//                    String ex48 = "";
//                    if(JCB_ex48_01.isSelected()){
//                        ex48 += "Normal. ";
//                    }
//                    if(JCB_ex48_02.isSelected()){
//                        ex48 += "Reduzida. ";
//                    }
//                    if(JCB_ex48_03.isSelected()){
//                        ex48 += "Aumentada. ";
//                    }
//                    if(JCB_ex48_04.isSelected()){
//                        ex48 += "Muito variada. ";
//                    }
//                    c.setEx48(ex48);
//            //Ritmo
//                    String ex49 = "";
//                    if(JCB_ex49_01.isSelected()){
//                        ex49 += "Adequado. ";
//                    }
//                    if(JCB_ex49_01.isSelected()){
//                        ex49 += "Cadenciada. ";
//                    }
//                    if(JCB_ex49_01.isSelected()){
//                        ex49 += "Alongada. ";
//                    }
//                    if(JCB_ex49_04.isSelected()){
//                        ex49 += "Precipitada. ";
//                    }
//                    c.setEx49(ex49);
//            //Energia da emissão
//                    String ex50 = "";
//                    if(JCB_ex50_01.isSelected()){
//                        ex50 += "Suficiente. ";
//                    }
//                    if(JCB_ex50_02.isSelected()){
//                        ex50 += "Marcante. ";
//                    }
//                    if(JCB_ex50_03.isSelected()){
//                        ex50 += "Reduzida. ";
//                    }
//                    c.setEx50(ex50);
//            //Entonação
//                    String ex51 = "";
//                    if(JCB_ex51_01.isSelected()){
//                        ex51 += "Adequada. ";
//                    }
//                    if(JCB_ex51_02.isSelected()){
//                        ex51 += "Pouco marcante. ";
//                    }
//                    if(JCB_ex51_03.isSelected()){
//                        ex51 += "Inadequada. ";
//                    }
//                    c.setEx51(ex51);
//            //Resistencia vocal (não mantem)
//                    String ex52 = "";
//                    if(JCB_ex52_01.isSelected()){
//                        ex52 += "Qualidade vocal. ";
//                    }
//                    if(JCB_ex52_02.isSelected()){
//                        ex52 += "Velocidade. ";
//                    }
//                    if(JCB_ex52_03.isSelected()){
//                        ex52 += "Altura. ";
//                    }
//                    if(JCB_ex52_04.isSelected()){
//                        ex52 += "Dinâmica respiratória. ";
//                    }
//                    if(JCB_ex52_05.isSelected()){
//                        ex52 += "Ressonância. ";
//                    }
//                    if(JCB_ex52_06.isSelected()){
//                        ex52 += "Outros. ";
//                    }
//                    if(JCB_ex52_07.isSelected()){
//                        ex52 += "Articulação. ";
//                    }
//                    if(JCB_ex52_08.isSelected()){
//                        ex52 += "Intensidade. ";
//                    }
//                    c.setEx52(ex52);
//            //Parou o teste antes do fim
//                    c.setEx53(JCB_ex53.getText());
//            //Dinâmica respiratória
//                    String ex54 = "";
//                    if(JCB_ex54_01.isSelected()){
//                        ex54 += "Superior. ";
//                    }
//                    if(JCB_ex54_02.isSelected()){
//                        ex54 += "Ar de reserva. ";
//                    }
//                    if(JCB_ex54_03.isSelected()){
//                        ex54 += "Inspiração insuficiente. ";
//                    }
//                    if(JCB_ex54_04.isSelected()){
//                        ex54 += "Expiração insuficiente. ";
//                    }
//                    if(JCB_ex54_05.isSelected()){
//                        ex54 += "Ruidosa. ";
//                    }
//                    if(JCB_ex54_06.isSelected()){
//                        ex54 += "Invertida. ";
//                    }
//                    if(JCB_ex54_07.isSelected()){
//                        ex54 += "Ciclos curtos. ";
//                    }
//                    if(JCB_ex54_08.isSelected()){
//                        ex54 += "Expiração excessiva. ";
//                    }
//                    c.setEx54(ex54);
//            //Tipo
//                    String ex55 = "";
//                    if(JCB_ex55_01.isSelected()){
//                        ex55 += "Superior. ";
//                    }
//                    if(JCB_ex55_02.isSelected()){
//                        ex55 += "Media. ";
//                    }
//                    if(JCB_ex55_03.isSelected()){
//                        ex55 += "Inferior. ";
//                    }
//                    if(JCB_ex55_04.isSelected()){
//                        ex55 += "Completa. ";
//                    }
//                    c.setEx55(ex55);
//            //Modo
//                    String ex56 = "";
//                    if(JCB_ex56_01.isSelected()){
//                        ex56 += "Bucal. ";
//                    }
//                    if(JCB_ex56_02.isSelected()){
//                        ex56 += "Nasal. ";
//                    }
//                    if(JCB_ex56_03.isSelected()){
//                        ex56 += "Buco nasal. ";
//                    }
//                    c.setEx56(ex56);
//            //Estruturas de fonação
//                    String ex57 = "";
//                    if(JCB_ex57_01.isSelected()){
//                        ex57 += "Adequadas. ";
//                    }
//                    if(JCB_ex57_02.isSelected()){
//                        ex57 += "Alteradas. ";
//                    }
//                    ex57+= JTF_ex57_03.getText();
//                    c.setEx57(ex57);
//            //Apresenta alteração vocal após a manipulação digital da laringe?
//                    if(JCB_ex58_01.isSelected()){
//                        c.setEx58("Sim");
//                    }
//                    if(JCB_ex58_02.isSelected()){
//                        c.setEx58("Não");
//                    }
//            //Avaliação corporal - hipertonicidade
//                    String ex59 = "";
//                    if(JCB_ex59_01.isSelected()){
//                        ex59 += "Face. ";
//                    }
//                    if(JCB_ex59_02.isSelected()){
//                        ex59 += "Cintura escapular. ";
//                    }
//                    if(JCB_ex59_03.isSelected()){
//                        ex59 += "Peito. ";
//                    }
//                    c.setEx59(ex59);
//            //Fluencia da fala
//                    String ex60 = "";
//                    if(JCB_ex60_01.isSelected()){
//                        ex60 += "Adequada. ";
//                    }
//                    if(JCB_ex60_02.isSelected()){
//                        ex60 += "Pouco marcante. ";
//                    }
//                    if(JCB_ex60_03.isSelected()){
//                        ex60 += "Inadequada. . ";
//                    }
//                    c.setEx60(ex60);
//            //Construção sintática
//                    String ex61 = "";
//                    if(JCB_ex61_01.isSelected()){
//                        ex61 += "Adequada. ";
//                    }
//                    if(JCB_ex61_02.isSelected()){
//                        ex61 += "Pouco marcante. ";
//                    }
//                    if(JCB_ex61_03.isSelected()){
//                        ex61 += "Inadequada. . ";
//                    }
//                    c.setEx61(ex61);
//            //Expressão de ideias
//                    String ex62 = "";
//                    if(JCB_ex62_01.isSelected()){
//                        ex62 += "Adequada. ";
//                    }
//                    if(JCB_ex62_02.isSelected()){
//                        ex62 += "Pouco marcante. ";
//                    }
//                    if(JCB_ex62_03.isSelected()){
//                        ex62 += "Inadequada. . ";
//                    }
//                    c.setEx62(ex62);
//            //Tempo maximo de fonação
//                    String ex63 = "";
//                    // /a/
//                    c.setEx63_a1(JTF_ex63_a1.getText());
//                    c.setEx63_a2(JTF_ex63_a2.getText());
//                    c.setEx63_a3(JTF_ex63_a3.getText());
//                    c.setEx63_a4(JTF_ex63_a4.getText());
//                    // /i/
//                    c.setEx63_i1(JTF_ex63_i1.getText());
//                    c.setEx63_i2(JTF_ex63_i2.getText());
//                    c.setEx63_i3(JTF_ex63_i3.getText());
//                    c.setEx63_i4(JTF_ex63_i4.getText());
//                    // /u/
//                    c.setEx63_u1(JTF_ex63_u1.getText());
//                    c.setEx63_u2(JTF_ex63_u2.getText());
//                    c.setEx63_u3(JTF_ex63_u3.getText());
//                    c.setEx63_u4(JTF_ex63_u4.getText());
//                    // /s/
//                    c.setEx63_s1(JTF_ex63_s1.getText());
//                    c.setEx63_s2(JTF_ex63_s2.getText());
//                    c.setEx63_s3(JTF_ex63_s3.getText());
//                    c.setEx63_s4(JTF_ex63_s4.getText());
//                    // /z/
//                    c.setEx63_z1(JTF_ex63_z1.getText());
//                    c.setEx63_z2(JTF_ex63_z2.getText());
//                    c.setEx63_z3(JTF_ex63_z3.getText());
//                    c.setEx63_z4(JTF_ex63_z4.getText());
//                    
//                    //numero
//                    c.setEx63_n(JTF_ex63_n.getText());
//                    //segundo
//                    c.setEx63_s(JTF_ex63_s.getText());
//                    
//                    // Caixas
//                    if(JTF_ex63_01.isSelected()){
//                        ex63 += "Compatível com a idade. ";
//                    }
//                    if(JTF_ex63_02.isSelected()){
//                        ex63 += "Incompatível com a idade. ";
//                    }
//                    if(JTF_ex63_03.isSelected()){
//                        ex63 += "Compatível com o sexo. ";
//                    }
//                    if(JTF_ex63_04.isSelected()){
//                        ex63 += "Incompatível com o sexo. ";
//                    }
//                    if(JTF_ex63_06.isSelected()){
//                        ex63 += ">=01. ";
//                    }
//                    if(JTF_ex63_05.isSelected()){
//                        ex63 += "<=01. ";
//                    }
//                    c.setEx63(ex63);
//                    
//            //Sugestivo de
//                    String ex64 = "";
//                    if(JTF_ex64_01.isSelected()){
//                        ex64 += "Nódulos. ";
//                    }
//                    if(JTF_ex64_02.isSelected()){
//                        ex64 += "Fendas. ";
//                    }
//                    if(JTF_ex64_03.isSelected()){
//                        ex64 += "Dinâmica respiratória. ";
//                    }
//                    if(JTF_ex64_04.isSelected()){
//                        ex64 += "Normal. ";
//                    }
//                    if(JTF_ex64_05.isSelected()){
//                        ex64 += "Outras. ";
//                    }
//                    c.setEx64(ex64);
//            //Parecer fonoaudiológico
//                    c.setEx65(JTF_ex65.getText());
//            //Conduta
//                    c.setEx66(JTF_ex66.getText());
//            //Resultado
//                    String ex67 = "";
//                    if(JCB_ex67_01.isSelected()){
//                        ex67+="Apto.";
//                    }
//                    if(JCB_ex67_02.isSelected()){
//                        ex67+="Inapto.";
//                    }
//                    if(JCB_ex67_03.isSelected()){
//                        ex67+="Apto com restrições.";
//                    }
//                    c.setEx67(ex67);
//                    
//              //Resultado
//                    c.setEx68(JTF_ex67.getText());
//                    
//		s.save(c);
//		
//		s.getTransaction().commit();
//                JOptionPane.showMessageDialog(this, "Cadastro salvo com sucesso!");
//    }
//    
//    public void imprimiCadastro() throws JRException {
//        
//        String driver = "org.postgresql.Driver";
//        String user   = "postgres";
//        String senha = "postgres";
//        String url   = "jdbc:postgresql://localhost:5432/vocalexa";
//        
//        try
//        {
//            Class.forName(driver);
//            
//            Connection con = (Connection) DriverManager.getConnection(url, user, senha);
//            
//            String query = "SELECT * FROM vocalexa_funcionario, vocalexa_exames "
//                    + "WHERE vocalexa_funcionario.funcionario_rg = '"
//                    + JTF_busca_rg.getText()+"' AND vocalexa_exames.ex_data = '"
//                    + JTF_dataevento.getText()+"'";
//            
//            PreparedStatement cmd;
//            
//            cmd = con.prepareStatement(query);
//            
//            
//            ResultSet rs;
//            
//            rs = cmd.executeQuery();
//            
//            
//            JRResultSetDataSource jrRS = new JRResultSetDataSource( rs );
//            
//            JasperPrint jasperPrint = JasperFillManager.fillReport (
//                    "C:/Program Files/Vocalexa/Exame_Completo.jasper", new HashMap(), jrRS);
//                    JasperViewer.viewReport(jasperPrint, false);
//
//        }
//        catch (ClassNotFoundException | SQLException ex)
//        {
//            System.err.print(ex.getMessage());
//        }
//        catch (JRException ex){
//            String erro = ex.getMessage();
//            JOptionPane.showMessageDialog(this, erro, "Erro ao gerar relatório", ERROR);
//        }
//        
//    }
//
//    private void metodo_valor_aiu() {
//       double a = Double.parseDouble(JTF_ex63_a4.getText());
//       double i = Double.parseDouble(JTF_ex63_i4.getText());
//       double u = Double.parseDouble(JTF_ex63_u4.getText());
//       double total = (a+i+u)/3;
//       
//       if(total>=14 && total <18 && JTF_busca_sexo.getText().equals("Feminino")){
//           JTF_ex63_01.setSelected(true);
//           JTF_ex63_02.setSelected(false);           
//           JTF_ex63_03.setSelected(true);
//           JTF_ex63_04.setSelected(false);
//       }else{
//           JTF_ex63_01.setSelected(false);
//           JTF_ex63_02.setSelected(true);           
//           JTF_ex63_03.setSelected(false);
//           JTF_ex63_04.setSelected(true);
//       }
//       if(total>=18 && JTF_busca_sexo.getText().equals("Masculino")){
//           JTF_ex63_01.setSelected(true);
//           JTF_ex63_02.setSelected(false);           
//           JTF_ex63_03.setSelected(true);
//           JTF_ex63_04.setSelected(false);
//       }else{
//           JTF_ex63_01.setSelected(false);
//           JTF_ex63_02.setSelected(true);           
//           JTF_ex63_03.setSelected(false);
//           JTF_ex63_04.setSelected(true);
//       }
//    }
//
//    private void metodo_valor_sz() {
//        float s = Float.parseFloat(JTF_ex63_s4.getText());
//        float z = Float.parseFloat(JTF_ex63_z4.getText());
//        float total = (s+z)/2;
//        if(total >= 1.2){
//            JTF_ex64_02.setSelected(true);
//        }else{
//            JTF_ex64_04.setSelected(true);
//        }
//    }

}
